### ISSUE TITLE
DevPwd_InvalidSalt

### ISSUE THREAD

**Issue by p2p-sys** [khoanguyen-3fc/dh-p2p#2]
It is possible to update the protocol. On firmware 2023 this error

python3 main.py 89B0A4EAAABBBCC

> :55246 <<< www.easy4ipcloud.com:8800
HTTP/1.1 403 Forbidden
CSeq: 5
Content-Type: 
Content-Length: 95

<body><ErrCode>4</ErrCode><Error>DevPwd_InvalidSalt</Error><Policy>p2p,udprelay</Policy></body>
Error: Forbidden

**Comment by khoanguyen-3fc** [comment]
I've noticed that newer clients include device credentials when creating a P2P channel. However, to simplify the process and prioritize user privacy (since other users won't need to include device credentials when reporting issues), I've chosen to stick with the older protocol.

Could you provide additional details? This includes the device model, a pcap dump, and/or a link to download a Windows client compatible with your device. If possible, an official link like [this one](https://kbvisiongroup.com/support/download-center.html) would be ideal.

I'll do my best to avoid requesting your device credentials. However, it's challenging to guarantee the code's compatibility since my device doesn't require them. If you're open to it, would you consider implementing it directly? I'd be more than happy to merge it.

**Comment by p2p-sys** [comment]
Account for test:
9B0A4EDPAZ705D6
login testp2p
password Test123!

**Comment by khoanguyen-3fc** [comment]
Positive update, I was able to capture the packets using the newer client!

However, addressing this seems like a bit of a rabbit hole, and unfortunately, I can only dedicate my free time to it, which might extend over the course of weeks or months.

**Comment by khoanguyen-3fc** [comment]
Quick update, I was able to reproduce the `DevAuth` field, it use HMAC with SHA256 hash.

But I'm also trying to figure out the encryption method for the `LocalAddr` field, it seems to involve some kind of KDF + AES.

@p2p-sys side question, how was you able to find the password for the `cba1b29e32cb17aa46b8ff9e73c7f40b` user?

**Comment by p2p-sys** [comment]
@khoanguyen-3fc I have sent an invitation to my project, please accept it

**Comment by khoanguyen-3fc** [comment]
You can take a look at my latest commit (db283e9075635f5b6d2073422e02e720f2dd0ee9) for the Python implementation. Feel free to test it with the `-t 1` argument.

However, I'm still unable to get it to pass the PTCP handshake with the device. Do you have any ideas?

**Comment by khoanguyen-3fc** [comment]
Thanks to your help, I've been able to properly handle the STUN protocol.
